export enum Direction {
  NORTH = 'north',
  SOUTH = 'south',
  WEST = 'west',
  EAST = 'east',
}

export enum TileType {
  YITONG = 'yitong',
  ERTONG = 'ertong',
  SANTONG = 'santong',
  SITONG = 'sitong',
  WUTONG = 'wutong',
  LIUTONG = 'liutong',
  QITONG = 'qitong',
  BATONG = 'batong',
  JIUTONG = 'jiutong',
  YITIAO = 'yitiao',
  ERTIAO = 'ertiao',
  SANTIAO = 'santiao',
  SITIAO = 'sitiao',
  WUTIAO = 'wutiao',
  LIUTIAO = 'liutiao',
  QITIAO = 'qitiao',
  BATIAO = 'batiao',
  JIUTIAO = 'jiutiao',
  YIWAN = 'yiwan',
  ERWAN = 'erwan',
  SANWAN = 'sanwan',
  SIWAN = 'siwan',
  WUWAN = 'wuwan',
  LIUWAN = 'liuwan',
  QIWAN = 'qiwan',
  BAWAN = 'bawan',
  JIUWAN = 'jiuwan',
  HONGZHONG = 'hongzhong',
  FACAI = 'facai',
  BAIBAN = 'baiban',
  DONG = 'dong',
  XI = 'xi',
  NAN = 'nan',
  BEI = 'bei',
  HUA1 = 'hua1',
  HUA2 = 'hua2',
  HUA3 = 'hua3',
  HUA4 = 'hua4',
  HUAONE = 'huaone',
  HUATWO = 'huatwo',
  HUATHREE = 'huathree',
  HUAFOUR = 'huafour',
}
