import 'atat-common/lib/styles/index.css';
import 'atat-common/lib/modules/scrollable/index.css';
import 'atat-common/lib/modules/door/index.css';
import 'atat-common/lib/modules/audio/index.css';
import 'atat-common/lib/modules/scroll/index.css';
import 'atat-common/lib/modules/crystal/index.css';
import 'atat-common/lib/modules/lamp/index.css';
import 'atat-common/lib/modules/resume/index.css';
import './index.less';
